name: build

on:
    push:
        branches: [main]
        paths:
            - .github/**
            - src/**
            - test/**
            - Makefile
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3360000"
    SQLITE_BRANCH: "3.36"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  make compile-linux
                  make ctest-all
                  make test-all

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: make compile-windows

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: make compile-macos
