name: win32

on:
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3360000"
    SQLITE_BRANCH: "3.36"

jobs:
    build:
        name: Build for 32-bit Windows
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Install MSYS2 and 'mingw-w64-i686-toolchain'
              uses: msys2/setup-msys2@v2
              with:
                  cache: true
                  install: mingw-w64-i686-toolchain
                  update: true

            - name: Build
              shell: bash
              run: |
                  $RUNNER_TEMP/msys64/msys2_shell.cmd -defterm -no-start -mingw32 -lc "mingw32-make compile-windows-x86"
                  make compile-windows
